[project]
name = 'Stacks-Web3-Workshop'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.Simple-DeFi-Staking]
path = 'contracts/Simple-DeFi-Staking.clar'
clarity_version = 3
epoch = 'latest'
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false

[repl.remote_data]
enabled = false
api_url = 'https://api.hiro.so'
